version: 2.1

jobs:
  sonarcloud-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: medium
    steps:
      - checkout

      # Run SonarCloud analysis
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=ST10258256_INSY7314-POE-Final-SecurityAPI \
              -Dsonar.organization=st10258256 \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.coverage.exclusions=** 

    trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Run Trivy filesystem scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL ./Backend


  newman-tests:
    docker:
      - image: postman/newman:5.3.0
    steps:
      - checkout
      - run:
          name: Run API Tests with Newman
          command: |
            echo "Running Newman tests against deployed API..."
            newman run tests/api/banking-api.postman_collection.json \
              -e tests/api/banking-api.postman_environment.json \
              --delay-request 200 \
              --reporters cli,junit \
              --reporter-junit-export test-results/newman-results.xml


workflows:
  version: 2
  build:
    jobs:
      - sonarcloud-analysis:
          context: SonarCloud
      - trivy-scan
      - newman-tests:
          requires:
            - sonarcloud-analysis
            - trivy-scan
