version: 2.1

jobs:
  sonarcloud-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=ST10258256_INSY7314-POE-Final-SecurityAPI \
              -Dsonar.organization=st10258256 \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.coverage.exclusions=**

  trivy-scan:
    machine: {}   
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t securityapi ./Backend
      - run:
          name: Run Trivy scan
          command: trivy image --exit-code 1 --severity HIGH,CRITICAL securityapi || true

  newman-tests:
    docker:
      - image: postman/newman:5.3.0
    steps:
      - checkout
      - run:
          name: Run Newman API Tests
          working-directory: Backend.Tests
          run: |
            npm install -g newman
            newman run banking-api.postman_collection.json \
            -e banking-api.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export newman-results.xml


workflows:
  version: 2
  build:
    jobs:
      - sonarcloud-analysis:
          context: SonarCloud
      - trivy-scan:
          requires:
            - sonarcloud-analysis
      - newman-tests:
          requires:
            - sonarcloud-analysis
            - trivy-scan
