version: 2.1

jobs:
  sonarcloud-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=ST10258256_INSY7314-POE-Final-SecurityAPI \
              -Dsonar.organization=st10258256 \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.coverage.exclusions=**

  trivy-scan:
    machine: {}   
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t securityapi ./Backend
      - run:
          name: Run Trivy scan
          command: trivy image --exit-code 1 --severity HIGH,CRITICAL securityapi || true

  newman-tests:
  docker:
    - image: cimg/dotnet:8.0-node
  steps:
    - checkout
    - run:
        name: Install Newman
        command: npm install -g newman
    - run:
        name: Start Backend
        command: |
          echo "Starting Backend..."
          dotnet run --project Backend/Backend.csproj --urls "http://0.0.0.0:5162" &
    - run:
        name: Wait for Backend
        command: |
          echo "Waiting for backend to be ready..."
          until curl -s http://localhost:5162/swagger/index.html >


workflows:
  version: 2
  build-and-test:
    jobs:
      - sonarcloud-analysis:
          context: SonarCloud
      - trivy-scan:
          requires:
            - sonarcloud-analysis
      - newman-tests:
          requires:
            - sonarcloud-analysis
            - trivy-scan
